# Generated by Django 6.0.4 on 2026-06-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collabsession',
            old_name='slud',
            new_name='slug',
        ),
    ]
